name: Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: current
    - name: Install pnpm and dependencies
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: true
    - name: Lint
      run: pnpm lint:check
